# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: News
    identifier: a1692702
    url: /#news
    weight: 10
  - name: Research
    identifier: c75c884d
    url: /#research
    weight: 20
  - name: Contact
    identifier: b28abf10
    url: /#contact
    weight: 40
  - name: CV
    identifier: 825be82c
    url: /#cv
    weight: 30
