hugoblox:
  schema: "2.0"
  identity:
    name: Ruotong Gao's Personal Website
    type: person
    tagline: PhD Student @University of Maryland
    description: "Ruotong is a PhD student in the College of Information at the University of Maryland College Park, advised by Dr. Stephanie Valencia. "
    organization: University of Maryland
  theme:
    mode: system
    pack: coffee
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: lg
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: false
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {2026} {Ruotong Gao}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
